# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-UPS
version:      0.04
version_from: UPS.pm
installdirs:  site
requires:
    Class::Struct:                 0.58
    Crypt::SSLeay:                 
    LWP::UserAgent:                
    XML::Simple:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
